---
# vars file for pcf
StackName: pcf-stack
Region: us-east-1
NATKeyPair: us-east-1
OpsManInstanceType: t2.medium
AMIID: ami-e6bdd9f0
Route53Zone: alavinia.me
Route53Record: mon.alavinia.me
Route53Type: A

DecryptionPassphrase: mypass
AdminUserName: saedalav@gmail.com
AdminPassword: mypass
#OpsManagerIngress: 0.0.0.0/0
#RdsDBName: bosh
#RdsUsername: bosh
#RdsPassword: bosh2017
#SSLCertificateARN: arn:aws:acm:us-east-1:920949869295:certificate/57feaa67-78e3-4f09-b933-34c2244c17f5
#OpsManagerTemplate: https://s3.amazonaws.com/saedalav/ops-manager.json
#ElbPrefix: 
#AllowHttpOnElb: True



