---
#Author: Saed Alavinia 
#Email: saedalav@gmail.com 
#Github: github.com/saedalav 

# Vars for DirectorConfig Task
StackName: pcf-stack
DecryptionPassphrase: mypass
AdminUserName: saedalav@gmail.com
AdminPassword: mypass
Route53Record: mon.alavinia.me
Region: us-east-1
KeyPair: us-east-1
ssh_private_key: "{{ lookup('file', '~/.ssh/us-east-1.pem') }}"

